package com.learning.java_web.commons.responses;

public enum RestApiMessage {
    USER_NOT_FOUND,
    ADDRESS_NOT_FOUND,
    ADDRESS_NAME_INVALID,
    USERNAME_INVALID,
    PHONE_NUMBER_INVALID,
    EMAIL_INVALID,
    CATEGORY_NOT_FOUND,
    CATEGORY_CHILDREN_ALREADY_EXISTED,
    USERNAME_ALREADY_EXISTED,
    PHONE_NUMBER_ALREADY_EXISTED,
    EMAIL_ALREADY_EXISTED,
    CATEGORY_NAME_INVALID,
    USER_ID_INVALID,
    PARENT_ID_INVALID,
    PARENT_ID_CANNOT_EMPTY,
    BAD_REQUEST,
    NAME_ALREADY_EXISTED,
    PARENT_ID_ALREADY_EXISTED,
    CANNOT_DELETED_WHILE_CHILDREN_EXISTED
}
